[core]
color-theme = "Lapce Light"
icon-theme = "Material Icons"
custom-titlebar = false
modal = false

[terminal]
font-family = "Menlo"
font-size = 14
line-height = 20.0

[editor]
font-size = 15
atomic-soft-tabs = false
show-tab = false
show-bread-crumbs = false
scroll-beyond-last-line = false
hover-delay = 100
highlight-scope-lines = true
signature-label-code-block = false
render-whitespace = "none"
enable-completion-lens = true
bracket-pair-colorization = true
font-family = "Menlo"
enable-inline-completion = false
enable-error-lens = true
line-height = 1.3
sticky-header = true
cursor-surrounding-lines = 0
error-lens-end-of-line = false
error-lens-multiline = false
only-render-error-styling = true
completion-show-documentation = false
enable-inlay-hints = false
completion-width = 550

[ui]
scale = 1.0
tab-min-width = 80
header-height = 25
palette-width = 400
font-size = 12
open-editors-visible = false
font-family = "Menlo"
tab-separator-height = "Content"
hover-font-family = ""
status-height = 18
scroll-width = 10
list-line-height = 20

[lapce-cpp-clangd]
"volt.serverPath" = "/usr/bin/clangd"
"volt.serverArgs" = [
    "--enable-config"
]

